# Step 1: Specify the base image from the official Node.js repository
FROM node:18-alpine

# Set the working directory in the Docker container
WORKDIR /app

# Copy the package.json and package-lock.json (if available)
# COPY package.json package-lock.json* ./
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --only=production

# Copy the rest of the application code
COPY . .

# # Add a user and change file ownership
# RUN adduser -D appuser && chown -R appuser /app
# USER appuser

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["node", "app.js"]

# docker build -t crypto-splitter-server:latest .
# docker images | grep crypto-splitter-server
# docker run -p 3000:3000 crypto-splitter-server:latest

## Postgres 14.11
# docker pull postgres:14.11-bullseye
# docker run --name postgres14 -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 postgres:14.11-bullseye

